### ISSUE TITLE
It's not working anymore

### ISSUE THREAD

**Issue by brunocalado** [relick/FoundryVTT-Actor-Attribute-Lists#1]
It's not working anymore

Can you fix it?

**Comment by relick** [comment]
What foundry version are you running? What other mods do you have running? It works for me on foundry 0.7.8.

**Comment by brunocalado** [comment]
Savage Worlds, 

I have to use the console command to list the actor data motel...

Is it possible to fix it?

![image](https://user-images.githubusercontent.com/4999783/104022118-9a47a000-519e-11eb-90d0-722e3c7d0574.png)

**Comment by relick** [comment]
When you use the console command to get the data list, does any of what is listed there actually work in rolls? As far as I'm aware, what Actor Attribute Lists shows are the only attributes you can use in rolls. For example, `/r 1d6 + @agi` (from Actor Attribute Lists) will roll a d6 and a d4 but `/r 1d6 + @agility` (from the data object) will give an error. Since it is as limited as you have shown, that's something that the _Savage Worlds_ system makers need to fix.

**Comment by relick** [comment]
closing as inactive, if anyone runs into the same problem please create a new issue
